name: Cache Warmup

on:
  push:
    branches: [ main ]

jobs:
  warmup:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-android

      - name: Warm up cache
        run: ./gradlew assembleDebug testDebugUnitTest